version: '2'

services:
  gitbucket:
    build: .
    container_name: gitbucket
    hostname: gitbucket
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - volume:/root/.gitbucket
    env_file: ./env/gitbucket.env
    privileged: true
    tty: true
    stdin_open: true
    command: ["entry"]

volumes:
  volume:
    driver: local
