storage:
  image: busybox
  container_name: gitbucket-storage
  volumes:
    - /home/gitbucket/.gitbucket
    - /etc/localtime:/etc/localtime:ro
    - ./volume:/home/gitbucket/.gitbucket

server:
  build: .
  container_name: gitbucket
  hostname: gitbucket
  volumes:
    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - storage
  privileged: true
  tty: true
  stdin_open: true
