storage:
  build: storage
  container_name: gitbucket-storage
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./volume:/home/gitbucket/.gitbucket

server:
  build: server
  container_name: gitbucket-server
  hostname: gitbucket
  volumes:
    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - storage
  privileged: true
  tty: true
  stdin_open: true
