#!/bin/bash

if [ -n "$GITBUCKET_VERSION-" ]; then
   GITBUCKET_VERSION=4.3
fi

cd /root/tomcat/webapps
/usr/bin/wget https://github.com/gitbucket/gitbucket/releases/download/${GITBUCKET_VERSION}/gitbucket.war
/bin/chown -R root:root /root/.gitbucket
/root/tomcat/bin/startup.sh
/bin/bash
